name: Preschool
favicon: null
layout_spectrum: 0.2368250626605004
typography_spectrum: 0.8722091168165207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9689250395167619
  lightness: 0.8287332605104893
  saturation: 0.08982947212643921
  rhythmicContrast: 0.8356941109523177
purpose: []
